# Generated by Django 4.1.4 on 2023-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_books_total_rentat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='total_rentat',
            new_name='total_rented',
        ),
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('rented', 'rented '), ('sold', 'sold')], max_length=40, null=True),
        ),
    ]
